# Generated by Django 5.0.6 on 2026-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("adresse", models.TextField(blank=True)),
                ("nb_etages", models.PositiveSmallIntegerField(default=1)),
                ("accessibilite_pmr", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bâtiment",
                "verbose_name_plural": "Bâtiments",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ConflitHoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_conflit",
                    models.CharField(
                        choices=[
                            ("salle", "Conflit de salle"),
                            ("enseignant", "Conflit enseignant"),
                            ("formation", "Conflit formation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("resolu", models.BooleanField(default=False)),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conflit horaire",
                "verbose_name_plural": "Conflits horaires",
            },
        ),
        migrations.CreateModel(
            name="CreneauCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                (
                    "type_cours",
                    models.CharField(
                        choices=[
                            ("CM", "Cours magistral"),
                            ("TD", "Travaux dirigés"),
                            ("TP", "Travaux pratiques"),
                            ("projet", "Projet"),
                            ("examen", "Examen"),
                            ("autre", "Autre"),
                        ],
                        default="CM",
                        max_length=20,
                    ),
                ),
                (
                    "groupe",
                    models.CharField(
                        blank=True, help_text="Ex: Groupe A, TD1", max_length=20
                    ),
                ),
                ("semaine_debut", models.PositiveSmallIntegerField(default=1)),
                ("semaine_fin", models.PositiveSmallIntegerField(default=52)),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("hebdomadaire", "Hebdomadaire"),
                            ("bihebdomadaire", "Toutes les 2 semaines"),
                            ("mensuel", "Mensuel"),
                        ],
                        default="hebdomadaire",
                        max_length=20,
                    ),
                ),
                (
                    "semaines_paires",
                    models.BooleanField(
                        blank=True,
                        help_text="True=semaines paires, False=impaires, None=toutes",
                        null=True,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Créneau de cours",
                "verbose_name_plural": "Créneaux de cours",
                "ordering": ["jour", "creneau_horaire__ordre"],
            },
        ),
        migrations.CreateModel(
            name="CreneauHoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("libelle", models.CharField(blank=True, max_length=50)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "ordering": ["ordre", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("cours_rattrapage", "Cours de rattrapage"),
                            ("examen", "Examen"),
                            ("reunion", "Réunion"),
                            ("soutenance", "Soutenance"),
                            ("evenement", "Événement"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("nb_personnes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirmee", "Confirmée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("motif_refus", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["date", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("amphi", "Amphithéâtre"),
                            ("td", "Salle de TD"),
                            ("tp", "Salle de TP"),
                            ("info", "Salle informatique"),
                            ("labo", "Laboratoire"),
                            ("reunion", "Salle de réunion"),
                            ("visio", "Salle de visioconférence"),
                            ("autre", "Autre"),
                        ],
                        default="td",
                        max_length=20,
                    ),
                ),
                ("capacite", models.PositiveIntegerField()),
                ("etage", models.SmallIntegerField(default=0)),
                (
                    "equipements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["vidéoprojecteur", "tableau blanc", ...]',
                    ),
                ),
                ("accessibilite_pmr", models.BooleanField(default=False)),
                ("disponible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Salle",
                "verbose_name_plural": "Salles",
                "ordering": ["batiment", "code"],
            },
        ),
    ]
