# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("national", "Diplôme national"),
                            ("universite", "Diplôme d'université"),
                            ("propre", "Diplôme propre"),
                            ("co_diplome", "Co-diplôme"),
                            ("etablissement", "Diplôme d'établissement"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "niveau_grade",
                    models.CharField(
                        help_text="Ex: Licence, Master, Doctorat", max_length=50
                    ),
                ),
                (
                    "code_rncp",
                    models.CharField(
                        blank=True, help_text="Code RNCP France", max_length=20
                    ),
                ),
                ("credits_ects", models.PositiveSmallIntegerField(default=180)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Diplôme",
                "verbose_name_plural": "Diplômes",
            },
        ),
        migrations.CreateModel(
            name="CessionDiplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_obtention", models.DateField()),
                ("mention", models.CharField(blank=True, max_length=30)),
                (
                    "moyenne_finale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("numero_serie", models.CharField(max_length=50, unique=True)),
                ("pdf_path", models.CharField(max_length=500)),
                ("date_signature", models.DateTimeField(blank=True, null=True)),
                ("qr_verification", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annee_universitaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cessions_diplomes",
                        to="etablissement.anneeuniversitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cession de diplôme",
                "verbose_name_plural": "Cessions de diplôme",
            },
        ),
    ]
