# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diplomes', '0002_initial'),
        ('formations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cessiondiplome',
            name='signe_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_signes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diplome',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes_type', to='formations.formation'),
        ),
        migrations.AddField(
            model_name='cessiondiplome',
            name='diplome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cessions', to='diplomes.diplome'),
        ),
        migrations.AlterUniqueTogether(
            name='cessiondiplome',
            unique_together={('etudiant', 'diplome', 'annee_universitaire')},
        ),
    ]
