# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('emplois_du_temps', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('valide', 'Validé')], default='ouvert', max_length=20)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_global', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='emplois_du_temps.creneau')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appels', to='enseignants.personnel')),
            ],
            options={
                'ordering': ['-date', '-creneau__heure_debut'],
                'unique_together': {('creneau', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('absent_justifie', 'Absent justifié'), ('retard', 'Retard'), ('sortie_anticipee', 'Sortie anticipée'), ('dispense', 'Dispensé')], default='present', max_length=20)),
                ('retard_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sortie_heure', models.TimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('notifie_parent', models.BooleanField(default=False)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='presences.appel')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_valides', to='enseignants.personnel')),
                ('presence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificatif', to='presences.presence')),
            ],
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['eleve', 'appel'], name='presences_p_eleve_i_90f0e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('appel', 'eleve')},
        ),
    ]
