# Generated by Django 5.0.6 on 2026-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="attributs_acces",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Contraintes ABAC par permission (classes, matières, années, etc.).",
            ),
        ),
    ]
