# Generated by Django 5.0.6 on 2026-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0002_utilisateur_attributs_acces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(default="eleve", max_length=100),
        ),
    ]
