# Generated by Django 5.0.6 on 2026-09-22 04:28

import sis_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='mfa_secret',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=100),
        ),
    ]
