# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eleves", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raison_sociale", models.CharField(max_length=200)),
                ("siret", models.CharField(blank=True, max_length=20)),
                ("secteur", models.CharField(blank=True, max_length=100)),
                ("taille", models.CharField(blank=True, max_length=20)),
                ("adresse", models.TextField()),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact_nom", models.CharField(blank=True, max_length=200)),
                ("contact_fonction", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "ordering": ["raison_sociale"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_entreprise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_etablissement",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_soutenance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "note_finale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "rapport",
                    models.FileField(
                        blank=True, null=True, upload_to="stages/rapports/"
                    ),
                ),
                ("appreciation_globale", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Évaluation de stage",
                "verbose_name_plural": "Évaluations de stage",
            },
        ),
        migrations.CreateModel(
            name="SuiviStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("visite", "Visite sur site"),
                            ("appel", "Appel téléphonique"),
                            ("rapport", "Rapport écrit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("commentaires", models.TextField()),
                ("appreciation", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Suivi de stage",
                "verbose_name_plural": "Suivis de stage",
            },
        ),
        migrations.CreateModel(
            name="ConventionStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuteur_entreprise", models.CharField(max_length=200)),
                ("telephone_tuteur", models.CharField(max_length=20)),
                ("email_tuteur", models.EmailField(max_length=254)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("duree_heures", models.PositiveIntegerField()),
                (
                    "remuneration",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("missions", models.TextField()),
                ("horaires", models.CharField(blank=True, max_length=200)),
                ("pdf_path", models.CharField(max_length=500)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("signee_etudiant", "Signée élève"),
                            ("signee_entreprise", "Signée entreprise"),
                            ("signee_etablissement", "Signée établissement"),
                            ("complete", "Complète"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=30,
                    ),
                ),
                (
                    "date_signature_complete",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conventions_stage",
                        to="eleves.eleve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convention de stage",
                "verbose_name_plural": "Conventions de stage",
            },
        ),
    ]
