# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conventionstage",
            name="maitre_stage_etablissement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stages_suivis",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conventionstage",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conventions",
                to="stages.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="evaluationstage",
            name="convention",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation",
                to="stages.conventionstage",
            ),
        ),
        migrations.AddField(
            model_name="suivistage",
            name="convention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suivis",
                to="stages.conventionstage",
            ),
        ),
    ]
