# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discipline", "0001_initial"),
        ("eleves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conseildiscipline",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conseils_discipline",
                to="eleves.eleve",
            ),
        ),
    ]
