# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0002_initial'),
        ('eleves', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseildiscipline',
            name='membres',
            field=models.ManyToManyField(related_name='conseils_membre', to='enseignants.personnel'),
        ),
        migrations.AddField(
            model_name='conseildiscipline',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conseils_presides', to='enseignants.personnel'),
        ),
        migrations.AddField(
            model_name='incident',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='incident',
            name='rapporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_rapportes', to='enseignants.personnel'),
        ),
        migrations.AddField(
            model_name='incident',
            name='temoins',
            field=models.ManyToManyField(blank=True, related_name='incidents_temoins', to='enseignants.personnel'),
        ),
        migrations.AddField(
            model_name='conseildiscipline',
            name='incidents',
            field=models.ManyToManyField(related_name='conseils', to='discipline.incident'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='discipline.incident'),
        ),
        migrations.AddField(
            model_name='conseildiscipline',
            name='sanction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils', to='discipline.sanction'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['eleve', 'date_incident'], name='discipline__eleve_i_937bda_idx'),
        ),
    ]
