# Generated by Django 5.0.6 on 2026-09-22 04:28

import sis_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='iban',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rib',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=50),
        ),
    ]
