# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementFrais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("date_paiement", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("carte", "Carte bancaire"),
                            ("mobile_money", "Mobile Money"),
                            ("sepa", "Prélèvement SEPA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_externe", models.CharField(blank=True, max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("echec", "Échec"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="valide",
                        max_length=20,
                    ),
                ),
                ("recu_pdf", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="TypeFraisInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("libelle", models.CharField(max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("unique", "Unique"),
                            ("semestriel", "Semestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="annuel",
                        max_length=20,
                    ),
                ),
                ("obligatoire", models.BooleanField(default=True)),
                ("date_limite", models.DateField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type de frais d'inscription",
                "verbose_name_plural": "Types de frais d'inscription",
            },
        ),
        migrations.CreateModel(
            name="VersementBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_versement", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mode", models.CharField(default="virement", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Versement de bourse",
                "verbose_name_plural": "Versements de bourse",
                "ordering": ["-date_versement"],
            },
        ),
        migrations.CreateModel(
            name="Bourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sociale", "Bourse sur critères sociaux"),
                            ("merite", "Bourse au mérite"),
                            ("mobilite", "Bourse de mobilité"),
                            ("these", "Bourse de thèse"),
                            ("urgence", "Aide d'urgence"),
                            ("exoneration", "Exonération"),
                        ],
                        max_length=20,
                    ),
                ),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_verse",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("numero_dossier", models.CharField(max_length=50, unique=True)),
                ("conditions", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("accordee", "Accordée"),
                            ("refusee", "Refusée"),
                            ("suspendue", "Suspendue"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("motif_refus", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bourses",
                        to="etudiants.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bourse",
                "verbose_name_plural": "Bourses",
            },
        ),
        migrations.CreateModel(
            name="FactureFrais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("date_emission", models.DateField()),
                ("date_echeance", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("emise", "Émise"),
                            ("payee", "Payée"),
                            ("partielle", "Partiellement payée"),
                            ("en_retard", "En retard"),
                            ("annulee", "Annulée"),
                        ],
                        default="emise",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("pdf_path", models.CharField(blank=True, max_length=500)),
                ("qr_paiement", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="etudiants.etudiant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_emission"],
            },
        ),
    ]
