# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('ine', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Française', max_length=100)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email_personnel', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('pre_inscrit', 'Pré-inscrit'), ('inscrit', 'Inscrit'), ('redoublant', 'Redoublant'), ('suspendu', 'Suspendu'), ('sortant', 'Sortant'), ('diplome', 'Diplômé'), ('abandon', 'Abandon'), ('transfert', 'Transfert')], default='pre_inscrit', max_length=20)),
                ('regime', models.CharField(choices=[('formation_initiale', 'Formation initiale'), ('formation_continue', 'Formation continue'), ('alternance', 'Alternance'), ('apprentissage', 'Apprentissage')], default='formation_initiale', max_length=30)),
                ('boursier', models.BooleanField(default=False)),
                ('date_premiere_inscription', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/')),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_tel', models.CharField(blank=True, max_length=20)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=20)),
                ('rib_iban', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('statut', models.CharField(choices=[('provisoire', 'Provisoire'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='provisoire', max_length=20)),
                ('regime', models.CharField(default='formation_initiale', max_length=30)),
                ('bourse_id', models.CharField(blank=True, help_text='ID bourse CROUS', max_length=50)),
                ('pieces_fournies', models.JSONField(blank=True, default=list)),
                ('payeur', models.CharField(blank=True, max_length=200)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-annee_universitaire__date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_td', models.CharField(blank=True, max_length=20)),
                ('groupe_tp', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('modifiee', 'Modifiée par admin')], default='brouillon', max_length=20)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscription pédagogique',
                'verbose_name_plural': 'Inscriptions pédagogiques',
            },
        ),
        migrations.CreateModel(
            name='AcquisitionECTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('acquis', 'Acquis'), ('en_cours', 'En cours'), ('echec', 'Échec'), ('dispense', 'Dispensé')], default='en_cours', max_length=20)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credits_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions_ects', to='etablissement.anneeuniversitaire')),
            ],
            options={
                'verbose_name': 'Acquisition ECTS',
                'verbose_name_plural': 'Acquisitions ECTS',
            },
        ),
    ]
