# Generated by Django 5.0.6 on 2026-09-22 04:34

import sis_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_affectationecueindividuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero_securite_sociale',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='rib_iban',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=50),
        ),
    ]
