# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiants", "0002_initial"),
        ("formations", "0001_initial"),
        ("ue_ecue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliberation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ouverture", models.DateTimeField(auto_now_add=True)),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                ("nb_admis", models.PositiveIntegerField(default=0)),
                ("nb_ajournes", models.PositiveIntegerField(default=0)),
                ("nb_refuses", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes de délibération"),
                ),
                ("pv_pdf", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DecisionJury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("valide", "Validé"),
                            ("compense", "Compensé"),
                            ("ajourne", "Ajourné"),
                            ("refuse", "Refusé"),
                            ("reorientation", "Réorientation"),
                            ("absence_examen", "Absence injustifiée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("voix_pour", models.PositiveSmallIntegerField(default=0)),
                ("voix_contre", models.PositiveSmallIntegerField(default=0)),
                ("abstentions", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions_jury",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions_jury",
                        to="ue_ecue.ue",
                    ),
                ),
                (
                    "deliberation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="jurys.deliberation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisionGlobale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("admis", "Admis"),
                            ("admis_mention", "Admis avec mention"),
                            ("admis_sous_condition", "Admis sous condition"),
                            ("ajourne", "Ajourné"),
                            ("refuse", "Refusé"),
                            ("reorientation", "Réorientation"),
                            ("redoublement", "Redoublement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("mention", models.CharField(blank=True, max_length=30)),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions_globales",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "deliberation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions_globales",
                        to="jurys.deliberation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("lieu", models.CharField(max_length=200)),
                ("ordre_jour", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("convoque", "Convoqué"),
                            ("reuni", "Réuni"),
                            ("delibere", "Délibéré"),
                            ("cloture", "Clôturé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("pv_pdf", models.CharField(blank=True, max_length=500)),
                ("date_pv", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jurys",
                        to="formations.formation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
