# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissement", "0001_initial"),
        ("formations", "0003_initial"),
        ("jurys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jury",
            name="membres",
            field=models.ManyToManyField(
                related_name="jurys_membre", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="jury",
            name="parcours",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jurys",
                to="formations.parcours",
            ),
        ),
        migrations.AddField(
            model_name="jury",
            name="president",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jurys_presides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jury",
            name="secretaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jurys_secretaires",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jury",
            name="semestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jurys",
                to="etablissement.semestre",
            ),
        ),
        migrations.AddField(
            model_name="deliberation",
            name="jury",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliberation",
                to="jurys.jury",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="decisionjury",
            unique_together={("deliberation", "etudiant", "ue")},
        ),
        migrations.AlterUniqueTogether(
            name="decisionglobale",
            unique_together={("deliberation", "etudiant")},
        ),
    ]
