# Generated by Django 5.0.6 on 2026-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactEntreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("rh", "RH"),
                            ("tuteur", "Tuteur de stage"),
                            ("responsable", "Responsable"),
                            ("dirigeant", "Dirigeant"),
                            ("autre", "Autre"),
                        ],
                        default="tuteur",
                        max_length=20,
                    ),
                ),
                ("fonction", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact entreprise",
                "verbose_name_plural": "Contacts entreprise",
            },
        ),
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raison_sociale", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SA", "SA"),
                            ("SARL", "SARL"),
                            ("SAS", "SAS"),
                            ("EURL", "EURL"),
                            ("SCI", "SCI"),
                            ("Association", "Association"),
                            ("EPI", "Établissement public"),
                            ("Etranger", "Entreprise étrangère"),
                        ],
                        default="SARL",
                        max_length=30,
                    ),
                ),
                ("siret", models.CharField(blank=True, max_length=20)),
                ("siren", models.CharField(blank=True, max_length=10)),
                ("tva_intracommunautaire", models.CharField(blank=True, max_length=20)),
                (
                    "secteur",
                    models.CharField(
                        choices=[
                            ("informatique", "Informatique / Tech"),
                            ("industrie", "Industrie"),
                            ("finance", "Finance / Banque"),
                            ("conseil", "Conseil"),
                            ("sante", "Santé"),
                            ("education", "Éducation"),
                            ("energie", "Énergie"),
                            ("agro", "Agroalimentaire"),
                            ("bTP", "BTP"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("site_web", models.URLField(blank=True)),
                ("adresse", models.TextField()),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(default="France", max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="entreprises/"),
                ),
                (
                    "taille",
                    models.CharField(
                        blank=True, help_text="TPE, PME, ETI, GE", max_length=20
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
                "ordering": ["raison_sociale"],
            },
        ),
    ]
