# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveTuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_payeur', models.BooleanField(default=False)),
                ('est_contact_urgence', models.BooleanField(default=True)),
                ('autorise_acces_portail', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-annee_scolaire__date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('lien_parente', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur_legal', 'Tuteur légal'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('autorise_sortie', models.BooleanField(default=True)),
                ('autorise_photos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Française', max_length=100)),
                ('ine', models.CharField(blank=True, help_text='Identifiant National Élève', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('redoublant', 'Redoublant'), ('sortant', 'Sortant'), ('transfere', 'Transféré'), ('diplome', 'Diplômé'), ('abandon', 'Abandon')], default='inscrit', max_length=20)),
                ('date_inscription', models.DateField()),
                ('motif_sortie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/')),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('allergies', models.TextField(blank=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_tel', models.CharField(blank=True, max_length=20)),
                ('bourse', models.BooleanField(default=False)),
                ('transport', models.BooleanField(default=False)),
                ('cantine', models.BooleanField(default=False)),
                ('interne', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_actuels', to='classes.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='etablissement.etablissement')),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
