# Generated by Django 5.0.6 on 2026-09-22 04:28

import sis_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_affectationmatiereindividuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='allergies',
            field=sis_common.encryption.EncryptedTextField(blank=True),
        ),
    ]
