# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributionBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_attribution", models.CharField(max_length=50, unique=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "montant_mensuel",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspendue", "Suspendue"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("rib_iban", models.CharField(blank=True, max_length=34)),
                ("titulaire_compte", models.CharField(blank=True, max_length=200)),
                ("motif_suspension", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attribution de bourse",
                "verbose_name_plural": "Attributions de bourses",
            },
        ),
        migrations.CreateModel(
            name="TypeBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("merite", "Bourse au mérite"),
                            ("sociale", "Bourse sociale"),
                            ("excellence", "Bourse d'excellence"),
                            ("mobilite", "Bourse de mobilité"),
                            ("recherche", "Bourse de recherche"),
                            ("stage", "Bourse de stage"),
                            ("handicap", "Aide handicap"),
                            ("urgence", "Aide d'urgence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "montant_mensuel",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "duree_mois",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="Durée en mois"
                    ),
                ),
                (
                    "criteres_eligibilite",
                    models.TextField(blank=True, help_text="Critères détaillés"),
                ),
                (
                    "moyenne_minimale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Moyenne minimale requise",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "plafond_ressources",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Plafond de ressources familiales",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("pieces_requises", models.JSONField(blank=True, default=list)),
                ("quota_annuel", models.PositiveIntegerField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type de bourse",
                "verbose_name_plural": "Types de bourses",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="VersementBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.DateField(help_text="Premier jour du mois concerné")),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("effectue", "Effectué"),
                            ("rejete", "Rejeté"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("date_virement", models.DateField(blank=True, null=True)),
                ("reference_virement", models.CharField(blank=True, max_length=100)),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Versement de bourse",
                "verbose_name_plural": "Versements de bourses",
                "ordering": ["mois"],
            },
        ),
        migrations.CreateModel(
            name="DemandeBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lettre_motivation", models.TextField(blank=True)),
                (
                    "justificatifs",
                    models.JSONField(
                        blank=True, default=list, help_text="Liste des fichiers"
                    ),
                ),
                (
                    "revenus_declares",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "moyenne_actuelle",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("soumise", "Soumise"),
                            ("en_instruction", "En instruction"),
                            ("complete", "Dossier complet"),
                            ("incomplete", "Dossier incomplet"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                            ("liste_attente", "Liste d'attente"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_soumission", models.DateTimeField(blank=True, null=True)),
                ("date_decision", models.DateTimeField(blank=True, null=True)),
                ("motif_refus", models.TextField(blank=True)),
                ("commentaires_instruction", models.TextField(blank=True)),
                (
                    "rang_liste_attente",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annee_universitaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_bourses",
                        to="etablissement.anneeuniversitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de bourse",
                "verbose_name_plural": "Demandes de bourses",
                "ordering": ["-created_at"],
            },
        ),
    ]
