# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bourses", "0001_initial"),
        ("etudiants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="demandebourse",
            name="decision_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisions_bourses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demandebourse",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes_bourses",
                to="etudiants.etudiant",
            ),
        ),
        migrations.AddField(
            model_name="attributionbourse",
            name="demande",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribution",
                to="bourses.demandebourse",
            ),
        ),
        migrations.AddField(
            model_name="demandebourse",
            name="type_bourse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="demandes",
                to="bourses.typebourse",
            ),
        ),
        migrations.AddField(
            model_name="versementbourse",
            name="attribution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versements",
                to="bourses.attributionbourse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="demandebourse",
            unique_together={("etudiant", "type_bourse", "annee_universitaire")},
        ),
        migrations.AlterUniqueTogether(
            name="versementbourse",
            unique_together={("attribution", "mois")},
        ),
    ]
