# Generated by Django 5.0.6 on 2026-09-22 04:34

import sis_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributionbourse',
            name='rib_iban',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=34),
        ),
    ]
