# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('etablissement', '0001_initial'),
        ('salles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='prof_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='salle_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='salles.salle'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='etablissement.anneescolaire'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='classes',
            field=models.ManyToManyField(related_name='groupes', to='classes.classe'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='etablissement.etablissement'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='etablissement.etablissement'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='classes.matiere'),
        ),
        migrations.AddField(
            model_name='programmematiere',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='classes.classe'),
        ),
        migrations.AddField(
            model_name='programmematiere',
            name='enseignant_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes_principaux', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmematiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='classes.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('annee_scolaire', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('etablissement', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together={('matiere', 'niveau', 'ordre')},
        ),
        migrations.AlterUniqueTogether(
            name='programmematiere',
            unique_together={('classe', 'matiere')},
        ),
    ]
