# Generated by Django 5.0.6 on 2026-09-20 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="programmematiere",
            name="credits",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="programmematiere",
            name="enseignants",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "enseignant"},
                related_name="programmes_enseignes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupe",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="type",
            field=models.CharField(default="fondamentale", max_length=100),
        ),
    ]
