# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissement", "0001_initial"),
        ("structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="directeur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["directeur_dept", "doyen"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departements_diriges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ecoledoctorale",
            name="directeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecoles_dirigees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ecoledoctorale",
            name="universite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ecoles_doctorales",
                to="etablissement.universite",
            ),
        ),
        migrations.AddField(
            model_name="faculte",
            name="doyen",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["doyen", "vice_president"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facultes_dirigees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="faculte",
            name="universite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facultes",
                to="etablissement.universite",
            ),
        ),
        migrations.AddField(
            model_name="departement",
            name="faculte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departements",
                to="structure.faculte",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ecoledoctorale",
            unique_together={("universite", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="faculte",
            unique_together={("universite", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="departement",
            unique_together={("faculte", "code")},
        ),
    ]
