# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissement', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='note_seuil', max_length=20)),
                ('note_seuil', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('compensation_autorisee', models.BooleanField(default=True)),
                ('note_seuil_compensation', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capitalisation',
                'verbose_name_plural': 'Capitalisations',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('credits_ects', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(choices=[('F', 'Fondamentale'), ('S', 'Spécialité'), ('C', 'Complémentaire'), ('O', 'Optionnelle'), ('L', 'Libre')], default='F', max_length=2)),
                ('volume_horaire_cm', models.PositiveIntegerField(default=0, help_text='Heures CM')),
                ('volume_horaire_td', models.PositiveIntegerField(default=0, help_text='Heures TD')),
                ('volume_horaire_tp', models.PositiveIntegerField(default=0, help_text='Heures TP')),
                ('mh_global', models.CharField(choices=[('mutable', 'Mutable'), ('non_calculable', 'Non calculable'), ('calculable_separement', 'Calculable séparément')], default='calculable_separement', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='formations.maquetteformation')),
                ('parcours_autorises', models.ManyToManyField(blank=True, related_name='ues', to='formations.parcours')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='etablissement.semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['semestre', 'code'],
                'unique_together': {('maquette', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('capitalisee', 'UE capitalisée'), ('moyenne_ue', 'Moyenne UE'), ('note_minimale', 'Note minimale')], default='capitalisee', max_length=20)),
                ('note_minimale', models.DecimalField(blank=True, decimal_places=2, help_text='Si type = note_minimale', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ue_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis_requis', to='ue_ecue.ue')),
                ('ue_prereq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_prerequis_de', to='ue_ecue.ue')),
            ],
            options={
                'verbose_name': 'Prérequis',
                'verbose_name_plural': 'Prérequis',
                'unique_together': {('ue_cible', 'ue_prereq')},
            },
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('credits_ects', models.DecimalField(decimal_places=2, max_digits=4)),
                ('volume_horaire_cm', models.PositiveIntegerField(default=0)),
                ('volume_horaire_td', models.PositiveIntegerField(default=0)),
                ('volume_horaire_tp', models.PositiveIntegerField(default=0)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('programme', models.TextField(blank=True)),
                ('bibliographie', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='ue_ecue.ue')),
            ],
            options={
                'verbose_name': 'ECUE',
                'verbose_name_plural': 'ECUEs',
                'ordering': ['ue', 'code'],
                'unique_together': {('ue', 'code')},
            },
        ),
    ]
