# Generated by Django 5.0.6 on 2026-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ue_ecue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ue",
            name="type",
            field=models.CharField(default="F", max_length=100),
        ),
    ]
