# Generated by Django 5.0.6 on 2026-09-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0003_initial"),
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edxgradelog",
            name="event_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="EdxAssessmentMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsection_id", models.CharField(max_length=255)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="integration.edxcoursemapping",
                    ),
                ),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edx_assessment",
                        to="notes.evaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping évaluation EdX",
                "verbose_name_plural": "Mappings évaluations EdX",
            },
        ),
        migrations.AddConstraint(
            model_name="edxassessmentmapping",
            constraint=models.UniqueConstraint(
                fields=("course", "subsection_id"),
                name="unique_edx_assessment_superieur",
            ),
        ),
    ]
