# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignants', '0002_initial'),
        ('recherche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantchercheur',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chercheurs', to='recherche.laboratoire'),
        ),
    ]
