# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Universite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("universite_publique", "Université publique"),
                            ("universite_privee", "Université privée"),
                            ("grande_ecole", "Grande école"),
                            ("institut", "Institut supérieur"),
                            ("ecole_doctorale", "École doctorale"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sigle", models.CharField(blank=True, max_length=20)),
                ("ministere_tutelle", models.CharField(blank=True, max_length=200)),
                ("uai", models.CharField(blank=True, max_length=20)),
                ("adresse", models.TextField()),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(default="France", max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("site_web", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("systeme_notation", models.CharField(default="LMD", max_length=20)),
                ("credits_annee", models.PositiveSmallIntegerField(default=60)),
                ("accreditations", models.JSONField(blank=True, default=list)),
                (
                    "conventions_internationales",
                    models.JSONField(blank=True, default=list),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Université",
                "verbose_name_plural": "Universités",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="etablissement.universite",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnneeUniversitaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(help_text="Ex: 2026-2027", max_length=50)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("en_cours", models.BooleanField(default=False)),
                ("cloturee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "universite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annees_universitaires",
                        to="etablissement.universite",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_debut"],
                "unique_together": {("universite", "libelle")},
            },
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("impair", "Semestre impair (S1, S3, S5)"),
                            ("pair", "Semestre pair (S2, S4, S6)"),
                            ("unique", "Semestre unique"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("cloture", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annee_universitaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semestres",
                        to="etablissement.anneeuniversitaire",
                    ),
                ),
            ],
            options={
                "ordering": ["annee_universitaire", "numero"],
                "unique_together": {("annee_universitaire", "numero")},
            },
        ),
    ]
