# Generated by Django 5.0.6 on 2026-09-20 08:01

import django.core.validators
from django.db import migrations, models

import sis_common.establishments


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="universite",
            name="configuration_visio",
            field=models.JSONField(
                default=sis_common.establishments.default_live_configuration,
                validators=[sis_common.establishments.validate_live_configuration],
            ),
        ),
        migrations.AddField(
            model_name="universite",
            name="couleur_primaire",
            field=models.CharField(
                default="#0A3055",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$",
                        "Utilisez une couleur hexadécimale, par exemple #0A3055.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="universite",
            name="couleur_secondaire",
            field=models.CharField(
                default="#FFFFFF",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$",
                        "Utilisez une couleur hexadécimale, par exemple #FFFFFF.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="universite",
            name="fonctionnalites",
            field=models.JSONField(
                default=sis_common.establishments.default_establishment_features,
                validators=[sis_common.establishments.validate_establishment_features],
            ),
        ),
        migrations.AddField(
            model_name="universite",
            name="fuseau_horaire",
            field=models.CharField(
                default="UTC",
                max_length=64,
                validators=[sis_common.establishments.validate_timezone],
            ),
        ),
        migrations.AddField(
            model_name="universite",
            name="type_personnalise",
            field=models.CharField(
                blank=True,
                help_text="Libellé utilisé lorsque le type d'établissement est « autre ».",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="universite",
            name="type",
            field=models.CharField(
                choices=[
                    ("universite_publique", "Université publique"),
                    ("universite_privee", "Université privée"),
                    ("grande_ecole", "Grande école"),
                    ("institut", "Institut supérieur"),
                    ("ecole_doctorale", "École doctorale"),
                    ("autre", "Autre établissement"),
                ],
                max_length=30,
            ),
        ),
    ]
