# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bulletins", "0001_initial"),
        ("classes", "0001_initial"),
        ("eleves", "0001_initial"),
        ("etablissement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appreciationmatiere",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appreciations_matiere",
                to="eleves.eleve",
            ),
        ),
        migrations.AddField(
            model_name="appreciationmatiere",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appreciations",
                to="classes.matiere",
            ),
        ),
        migrations.AddField(
            model_name="appreciationmatiere",
            name="periode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appreciations",
                to="etablissement.periode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appreciationmatiere",
            unique_together={("eleve", "matiere", "periode")},
        ),
    ]
