# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cantine', '0001_initial'),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioncantine',
            name='eleve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_cantine', to='eleves.eleve'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('date', 'regime')},
        ),
        migrations.AddField(
            model_name='presencecantine',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences_cantine', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='presencecantine',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='cantine.menu'),
        ),
        migrations.AlterUniqueTogether(
            name='presencecantine',
            unique_together={('menu', 'eleve')},
        ),
    ]
