# Generated by Django 5.0.6 on 2026-09-20 09:37

import apps.examens.models
import django.core.validators
import django.db.models.deletion
import sis_common.exam_files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examens", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuveexamen",
            name="nombre_corrections",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Une correction simple ou une double correction indépendante.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.CreateModel(
            name="CopieExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_anonyme",
                    models.CharField(
                        default=apps.examens.models.generate_anonymous_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        storage=sis_common.exam_files.PrivateExamStorage(),
                        upload_to=sis_common.exam_files.exam_copy_upload_to,
                        validators=[sis_common.exam_files.validate_exam_copy],
                    ),
                ),
                ("empreinte_sha256", models.CharField(editable=False, max_length=64)),
                ("taille_octets", models.PositiveBigIntegerField(editable=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("deposee", "Déposée"),
                            ("affectee", "Affectée"),
                            ("correction", "En correction"),
                            ("a_moderer", "À modérer"),
                            ("finalisee", "Finalisée"),
                        ],
                        default="deposee",
                        max_length=20,
                    ),
                ),
                (
                    "note_finale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("moderee_le", models.DateTimeField(blank=True, null=True)),
                ("motif_moderation", models.TextField(blank=True)),
                ("deposee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "convocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copie",
                        to="examens.convocationexamen",
                    ),
                ),
                (
                    "deposee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies_examen_deposees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies_moderees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-deposee_le"],
            },
        ),
        migrations.CreateModel(
            name="AuditCopieExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "acteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_copies_examen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "copie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit",
                        to="examens.copieexamen",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="AffectationCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("assignee", "Assignée"),
                            ("en_cours", "En cours"),
                            ("soumise", "Soumise"),
                        ],
                        default="assignee",
                        max_length=20,
                    ),
                ),
                ("affectee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "affectee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations_correction",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correcteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections_assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "copie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="examens.copieexamen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorrectionCopie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.DecimalField(decimal_places=2, max_digits=5)),
                ("appreciation", models.TextField(blank=True)),
                ("soumise_le", models.DateTimeField(auto_now_add=True)),
                ("modifiee_le", models.DateTimeField(auto_now=True)),
                (
                    "affectation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction",
                        to="examens.affectationcorrection",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="copieexamen",
            index=models.Index(
                fields=["statut", "deposee_le"], name="examens_cop_statut_5d12fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="copieexamen",
            index=models.Index(
                fields=["convocation"], name="examens_cop_convoca_614870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditcopieexamen",
            index=models.Index(
                fields=["copie", "cree_le"], name="examens_aud_copie_i_5da006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affectationcorrection",
            index=models.Index(
                fields=["correcteur", "statut"], name="examens_aff_correct_7b42af_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="affectationcorrection",
            constraint=models.UniqueConstraint(
                fields=("copie", "ordre"), name="unique_ordre_correction_secondaire"
            ),
        ),
        migrations.AddConstraint(
            model_name="affectationcorrection",
            constraint=models.UniqueConstraint(
                fields=("copie", "correcteur"),
                name="unique_correcteur_copie_secondaire",
            ),
        ),
    ]
