# Generated by Django 5.0.6 on 2026-09-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examens", "0003_epreuveexamen_nombre_corrections_copieexamen_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionexamen",
            name="cloturee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="cloture_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="cloture_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats_examens_clotures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="publie_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="publie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats_examens_publies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="reouvert_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="reouvert_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats_examens_reouverts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="saisi_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="saisi_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats_examens_saisis",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="statut",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("submitted", "Soumis"),
                    ("verified", "Vérifié"),
                    ("validated", "Validé"),
                    ("published", "Publié"),
                    ("reopened", "Réouvert"),
                    ("closed", "Clôturé"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="type_resultat",
            field=models.CharField(
                choices=[("normal", "Ordinaire"), ("retake", "Rattrapage")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="valide_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats_examens_valides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="verifie_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats_examens_verifies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="resultatexamen",
            index=models.Index(
                fields=["statut", "type_resultat"],
                name="examens_res_statut_3bd0e4_idx",
            ),
        ),
    ]
