# Generated by Django 5.0.6 on 2026-09-20 10:16

import sis_common.academic_configuration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etablissement", "0002_etablissement_configuration_visio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="configuration_academique",
            field=models.JSONField(
                default=sis_common.academic_configuration.default_academic_configuration,
                validators=[
                    sis_common.academic_configuration.validate_academic_configuration
                ],
            ),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="systeme_periodes",
            field=models.CharField(default="trimestre", max_length=20),
        ),
        migrations.AlterField(
            model_name="etablissement",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="niveau",
            name="cycle",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="periode",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
