# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], max_length=20)),
                ('reference_externe', models.CharField(blank=True, help_text='N° chèque, transaction ID...', max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='valide', max_length=20)),
                ('recu_pdf', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicite', models.CharField(choices=[('unique', 'Unique'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='annuel', max_length=20)),
                ('obligatoire', models.BooleanField(default=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('partielle', 'Partiellement payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='emise', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='eleves.eleve')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
