# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('etablissement', '0001_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiements.facture'),
        ),
        migrations.AddField(
            model_name='typefrais',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_frais', to='etablissement.anneescolaire'),
        ),
        migrations.AddField(
            model_name='typefrais',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='types_frais', to='classes.classe'),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='paiements.typefrais'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture', 'statut'], name='paiements_p_facture_f1d248_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typefrais',
            unique_together={('annee_scolaire', 'code')},
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['eleve', 'statut'], name='paiements_f_eleve_i_5263ce_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_echeance'], name='paiements_f_date_ec_aba27e_idx'),
        ),
    ]
