# Generated by Django 5.0.6 on 2026-09-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sis_common.exam_files


class Migration(migrations.Migration):

    dependencies = [
        ("paiements", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="motif_rejet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="preuve_paiement",
            field=models.FileField(
                blank=True,
                null=True,
                storage=sis_common.exam_files.PrivateFinancialStorage(),
                upload_to=sis_common.exam_files.payment_proof_upload_to,
                validators=[sis_common.exam_files.validate_payment_proof],
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="verifie_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_verifies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("valide", "Validé"),
                    ("echec", "Échec"),
                    ("rejete", "Rejeté"),
                    ("rembourse", "Remboursé"),
                ],
                default="valide",
                max_length=20,
            ),
        ),
    ]
