# Generated by Django 5.0.6 on 2026-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('du', 'Diplôme universitaire'), ('certificat', 'Certificat'), ('ingenieur', "Diplôme d'ingénieur"), ('commerce', 'Diplôme de commerce')], max_length=20)),
                ('niveau', models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D1', 'Doctorat 1'), ('D2', 'Doctorat 2'), ('D3', 'Doctorat 3')], max_length=5)),
                ('duree_annees', models.PositiveSmallIntegerField(default=3)),
                ('nb_semestres', models.PositiveSmallIntegerField(default=6)),
                ('credits_total', models.PositiveSmallIntegerField(default=180)),
                ('accreditations', models.JSONField(blank=True, default=list)),
                ('date_accreditation', models.DateField(blank=True, null=True)),
                ('date_fin_accreditation', models.DateField(blank=True, null=True)),
                ('regime', models.CharField(choices=[('formation_initiale', 'Formation initiale'), ('formation_continue', 'Formation continue'), ('alternance', 'Alternance'), ('apprentissage', 'Apprentissage')], default='formation_initiale', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('debouches', models.TextField(blank=True)),
                ('conditions_admission', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='MaquetteFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.JSONField(default=dict, help_text='Structure des UE par semestre')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('archivee', 'Archivée')], default='brouillon', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maquette de formation',
                'verbose_name_plural': 'Maquettes de formation',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('specialisation', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
            },
        ),
    ]
