# Generated by Django 5.0.6 on 2026-09-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="niveau",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="formation",
            name="regime",
            field=models.CharField(default="formation_initiale", max_length=100),
        ),
        migrations.AlterField(
            model_name="formation",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
