# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("conseil_classe", "0001_initial"),
        ("eleves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appreciationconseil",
            name="eleve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appreciations_conseil",
                to="eleves.eleve",
            ),
        ),
        migrations.AddField(
            model_name="conseilclasse",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conseils",
                to="classes.classe",
            ),
        ),
    ]
