# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('numero_lot', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock médicament',
                'verbose_name_plural': 'Stock médicaments',
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('maladies_chroniques', models.JSONField(blank=True, default=list)),
                ('traitements', models.TextField(blank=True)),
                ('vaccinations', models.JSONField(blank=True, default=list)),
                ('medecin_traitant', models.CharField(blank=True, max_length=200)),
                ('telephone_medecin', models.CharField(blank=True, max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_derniere_visite', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
        migrations.CreateModel(
            name='VisiteInfirmerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('heure_arrivee', models.TimeField()),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(max_length=200)),
                ('symptomes', models.TextField(blank=True)),
                ('soins', models.TextField(blank=True)),
                ('traitement_administre', models.TextField(blank=True)),
                ('orientation', models.CharField(choices=[('retour_cours', 'Retour en cours'), ('sortie', 'Sortie autorisée'), ('urgence', 'Urgence médicale'), ('parents', 'Parents appelés'), ('hospitalisation', 'Hospitalisation')], default='retour_cours', max_length=30)),
                ('parents_prevenus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_infirmerie', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Visite infirmerie',
                'verbose_name_plural': 'Visites infirmerie',
                'ordering': ['-date'],
            },
        ),
    ]
