# Generated by Django 5.0.6 on 2026-09-22 04:28

from django.db import migrations

import sis_common.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('infirmerie', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='allergies',
            field=sis_common.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='groupe_sanguin',
            field=sis_common.encryption.EncryptedCharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='maladies_chroniques',
            field=sis_common.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='observations',
            field=sis_common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='traitements',
            field=sis_common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='vaccinations',
            field=sis_common.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='visiteinfirmerie',
            name='soins',
            field=sis_common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visiteinfirmerie',
            name='symptomes',
            field=sis_common.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visiteinfirmerie',
            name='traitement_administre',
            field=sis_common.encryption.EncryptedTextField(blank=True),
        ),
    ]
