# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpreuveExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField()),
                ('lieu', models.CharField(help_text='Bâtiment / amphithéâtre', max_length=200)),
                ('places_totales', models.PositiveIntegerField(default=0)),
                ('anonymat', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'Session 1 (normale)'), (2, 'Session 2 (rattrapage)')])),
                ('type', models.CharField(choices=[('normale', 'Normale'), ('rattrapage', 'Rattrapage'), ('exceptionnelle', 'Exceptionnelle')], default='normale', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloturee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['semestre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ConvocationExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_place', models.CharField(blank=True, max_length=10)),
                ('salle', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('convoque', 'Convoqué'), ('present', 'Présent'), ('absent', 'Absent'), ('dispense', 'Dispensé'), ('annule', 'Annulé')], default='convoque', max_length=20)),
                ('notifie', models.BooleanField(default=False)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Convocation examen',
                'verbose_name_plural': 'Convocations examen',
            },
        ),
    ]
