# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examens', '0001_initial'),
        ('ue_ecue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuveexamen',
            name='ecue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='ue_ecue.ecue'),
        ),
    ]
