# Generated by Django 5.0.6 on 2026-09-21 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examens", "0004_epreuveexamen_bareme_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultatExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("appreciation", models.TextField(blank=True)),
                ("numero_anonyme", models.CharField(blank=True, max_length=20)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("verified", "Vérifié"),
                            ("validated", "Validé"),
                            ("published", "Publié"),
                            ("reopened", "Réouvert"),
                            ("closed", "Clôturé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "type_resultat",
                    models.CharField(
                        choices=[("normal", "Ordinaire"), ("retake", "Rattrapage")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("admis", models.BooleanField(default=False)),
                ("mention", models.CharField(blank=True, max_length=30)),
                ("saisi_le", models.DateTimeField(blank=True, null=True)),
                ("verifie_le", models.DateTimeField(blank=True, null=True)),
                ("valide_le", models.DateTimeField(blank=True, null=True)),
                ("publie_le", models.DateTimeField(blank=True, null=True)),
                ("reouvert_le", models.DateTimeField(blank=True, null=True)),
                ("cloture_le", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cloture_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens_superieur_clotures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="examens.epreuveexamen",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats_examen",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "publie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens_superieur_publies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reouvert_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens_superieur_reouverts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens_superieur_saisis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens_superieur_valides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens_superieur_verifies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat d'examen",
                "verbose_name_plural": "Résultats d'examen",
            },
        ),
        migrations.AlterUniqueTogether(
            name="resultatexamen",
            unique_together={("epreuve", "etudiant")},
        ),
        migrations.AddIndex(
            model_name="resultatexamen",
            index=models.Index(
                fields=["statut", "type_resultat"],
                name="examens_res_statut_1b028c_idx",
            ),
        ),
    ]
