# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enseignants", "0004_initial"),
        ("etablissement", "0001_initial"),
        ("etudiants", "0003_initial"),
        ("formations", "0003_initial"),
        ("memoires", "0001_initial"),
        ("recherche", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jurymemoire",
            name="autres_membres",
            field=models.ManyToManyField(
                blank=True,
                related_name="jurys_memoire_autres",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jurymemoire",
            name="president",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jurys_memoire_presides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jurymemoire",
            name="rapporteurs",
            field=models.ManyToManyField(
                related_name="rapports_memoire", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="etudiant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoire",
                to="etudiants.etudiant",
            ),
        ),
        migrations.AddField(
            model_name="jurymemoire",
            name="memoire",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jury",
                to="memoires.memoire",
            ),
        ),
        migrations.AddField(
            model_name="soutenancememoire",
            name="jury",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soutenance",
                to="memoires.jurymemoire",
            ),
        ),
        migrations.AddField(
            model_name="sujetmemoire",
            name="annee_universitaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sujets_memoire",
                to="etablissement.anneeuniversitaire",
            ),
        ),
        migrations.AddField(
            model_name="sujetmemoire",
            name="co_encadreur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memoires_co_encadres",
                to="enseignants.enseignantchercheur",
            ),
        ),
        migrations.AddField(
            model_name="sujetmemoire",
            name="encadreur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memoires_encadres",
                to="enseignants.enseignantchercheur",
            ),
        ),
        migrations.AddField(
            model_name="sujetmemoire",
            name="formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sujets_memoire",
                to="formations.formation",
            ),
        ),
        migrations.AddField(
            model_name="sujetmemoire",
            name="laboratoire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sujets_memoire",
                to="recherche.laboratoire",
            ),
        ),
        migrations.AddField(
            model_name="memoire",
            name="sujet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memoires",
                to="memoires.sujetmemoire",
            ),
        ),
    ]
