# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleveNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_path", models.CharField(max_length=500)),
                (
                    "moyenne_generale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("mention", models.CharField(blank=True, max_length=30)),
                (
                    "credits_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "credits_valides",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("classement", models.PositiveIntegerField(blank=True, null=True)),
                ("effectif", models.PositiveIntegerField(blank=True, null=True)),
                ("date_emission", models.DateField()),
                ("signe", models.BooleanField(default=False)),
                ("date_signature", models.DateTimeField(blank=True, null=True)),
                ("numero_serie", models.CharField(max_length=50, unique=True)),
                ("qr_verification", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Relevé de notes",
                "verbose_name_plural": "Relevés de notes",
                "ordering": ["-semestre__date_fin"],
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_path", models.CharField(max_length=500)),
                ("credits_total", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "credits_valides",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "moyenne_ponderee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("mention_finale", models.CharField(blank=True, max_length=30)),
                ("diplome_prepare", models.CharField(blank=True, max_length=200)),
                ("date_emission", models.DateField()),
                ("numero_serie", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transcript",
                "verbose_name_plural": "Transcripts",
            },
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reussite", "Attestation de réussite"),
                            ("inscription", "Attestation d'inscription"),
                            ("comparabilite", "Attestation de comparabilité"),
                            ("relevé_notes", "Demande de relevé"),
                            ("diplome", "Attestation de diplôme"),
                            ("stage", "Attestation de stage"),
                            ("mobilite", "Attestation de mobilité"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pdf_path", models.CharField(max_length=500)),
                ("date_emission", models.DateField()),
                ("date_validite", models.DateField(blank=True, null=True)),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="etudiants.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attestation",
                "verbose_name_plural": "Attestations",
            },
        ),
    ]
