# Generated by Django 5.0.6 on 2026-09-19 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etablissement", "0001_initial"),
        ("etudiants", "0003_initial"),
        ("releves", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attestation",
            name="signe_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attestations_signees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relevenotes",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releves",
                to="etudiants.etudiant",
            ),
        ),
        migrations.AddField(
            model_name="relevenotes",
            name="semestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="releves",
                to="etablissement.semestre",
            ),
        ),
        migrations.AddField(
            model_name="relevenotes",
            name="signe_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="releves_signes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="annees",
            field=models.ManyToManyField(
                related_name="transcripts", to="etablissement.anneeuniversitaire"
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="etudiants.etudiant",
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="signe_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcripts_signes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relevenotes",
            unique_together={("etudiant", "semestre")},
        ),
    ]
